# tasks file for schubergphilis.SUSE15_CIS
- name: MAIN | show OS version
  debug:
    msg: OS VERSION - {{ ansible_os_family }} - {{ ansible_distribution_major_version
      }}
- name: Check OS family
  fail:
    msg: "This role can only be run against SUSE15/OpenSUSE15. \n {{ ansible_os_family\
      \ }}/{{ ansible_distribution }}/{{ ansible_distribution_major_version }} is\
      \ not supported."
  when:
  - not (ansible_os_family == 'Suse' and ansible_distribution_major_version in ['15'])
  tags:
  - always

- name: MAIN | Check ansible version
  fail:
    msg: You must use ansible 2.9 or greater
  when: ansible_version.full is version('2.9', '<')
  tags:
  - always

- include: prelim.yml
  become: yes
  tags:
  - always

- include: section1.yml
  become: yes
  when: suse15cis_section1
  tags:
  - suse15cis_section1

- include: section2.yml
  become: yes
  when: suse15cis_section2
  tags:
  - suse15cis_section2

- include: section3.yml
  become: yes
  when: suse15cis_section3
  tags:
  - suse15cis_section3

- include: section4.yml
  become: yes
  when: suse15cis_section4
  tags:
  - suse15cis_section4

- include: section5.yml
  become: yes
  when: suse15cis_section5
  tags:
  - suse15cis_section5

- include: section6.yml
  become: yes
  when: suse15cis_section6
  tags:
  - suse15cis_section6
